import type {
  AIProviderId,
  DepartmentDefinition,
  DepartmentId,
} from "./types";

export const AI_PROVIDERS: Record<
  AIProviderId,
  {
    name: string;
    configuration: "api-key" | "oauth" | "local-endpoint";
    defaultEndpoint?: string;
    notes: string;
  }
> = {
  codex: {
    name: "OpenAI Codex",
    configuration: "oauth",
    notes: "Coding-agent execution. Access depends on the configured Codex surface and account.",
  },
  openai: {
    name: "OpenAI (ChatGPT models via API)",
    configuration: "api-key",
    defaultEndpoint: "https://api.openai.com/v1",
    notes: "Model IDs and prices must be discovered from the connected account, not hard-coded.",
  },
  hermes: {
    name: "Hermes",
    configuration: "local-endpoint",
    notes: "OpenAI-compatible or custom Hermes deployment configured by the operator.",
  },
  anthropic: {
    name: "Anthropic Claude",
    configuration: "api-key",
    defaultEndpoint: "https://api.anthropic.com",
    notes: "Claude model IDs must be selected from the connected account.",
  },
  ollama: {
    name: "Ollama",
    configuration: "local-endpoint",
    defaultEndpoint: "http://localhost:11434",
    notes: "Local inference; availability is determined by models installed on the host.",
  },
  openrouter: {
    name: "OpenRouter",
    configuration: "api-key",
    defaultEndpoint: "https://openrouter.ai/api/v1",
    notes: "Routes to models enabled for the connected OpenRouter account.",
  },
  groq: {
    name: "Groq",
    configuration: "api-key",
    defaultEndpoint: "https://api.groq.com/openai/v1",
    notes: "Model availability and rate limits are read from the connected account.",
  },
  nvidia: {
    name: "NVIDIA NIM",
    configuration: "api-key",
    defaultEndpoint: "https://integrate.api.nvidia.com/v1",
    notes: "Supports hosted NIM APIs or an operator-supplied self-hosted NIM endpoint.",
  },
};

export const SPIRITUAL_AI_DEPARTMENTS = [
  {
    id: "ceo",
    name: "CEO Orchestrator",
    mission: "Set revenue-focused company objectives, delegate work, supervise risk, budgets and performance, and escalate exceptional decisions to the owner.",
    reportsTo: "owner",
    canDelegateTo: ["sales", "customer-care", "marketing", "product-management", "legal", "finance", "data-science-analytics", "seo-geo-aeo"],
    color: "#7C3AED",
    icon: "crown",
    capabilities: [
      "company.strategy.read", "company.strategy.write", "company.objectives.assign",
      "company.operations.monitor", "company.operations.pause", "company.budgets.allocate",
      "company.approvals.request", "company.escalations.notify",
    ],
    allowedConnectorKinds: ["ai-provider", "messaging", "analytics", "crm", "commerce", "payment"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft", "agent-loop-start", "agent-loop-pause"],
    approvalRequiredActions: ["ad-spend-change", "contract-or-terms-change", "payout-create", "bank-or-payment-settings-change", "credential-or-permission-change", "external-account-create"],
    prohibitedActions: ["Override an approval decision", "Reveal secrets or private customer data", "Represent itself as a human", "Optimize revenue through unlawful, deceptive, coercive or harmful conduct"],
    successMetrics: ["Recognized revenue", "Gross margin", "Cash runway", "Qualified pipeline", "Customer retention", "Approval and policy breach rate"],
  },
  {
    id: "sales",
    name: "Sales",
    mission: "Build a lawful, qualified pipeline and help prospects choose suitable Spiritual AI products.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#F59E0B",
    icon: "handshake",
    capabilities: [
      "sales.prospects.research", "sales.contacts.enrich", "sales.crm.read", "sales.crm.write",
      "sales.outreach.draft", "sales.outreach.send", "sales.calls.schedule", "sales.calls.place",
      "sales.proposals.prepare", "sales.deals.negotiate", "sales.contracts.request",
    ],
    allowedConnectorKinds: ["ai-provider", "email", "social-media", "telephony", "messaging", "crm", "contact-enrichment"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft", "prospect-enrichment"],
    approvalRequiredActions: ["commercial-email-send", "social-direct-message-send", "outbound-call-place", "contract-or-terms-change"],
    prohibitedActions: ["Buy or scrape unlawfully obtained contact lists", "Contact suppressed or opted-out people", "Impersonate a human", "Make unapproved medical, legal, spiritual-outcome or earnings claims"],
    successMetrics: ["Qualified opportunities", "Consent-compliant reply rate", "Conversion rate", "Sales cycle", "Revenue won", "Complaint and opt-out rate"],
  },
  {
    id: "customer-care",
    name: "Customer Care",
    mission: "Resolve customer questions safely, accurately and empathetically with prompt human escalation when needed.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#F97316",
    icon: "headphones",
    capabilities: ["support.knowledge.read", "support.tickets.read", "support.tickets.write", "support.messages.send", "support.refunds.request", "support.incidents.escalate"],
    allowedConnectorKinds: ["ai-provider", "email", "social-media", "telephony", "messaging", "crm", "payment"],
    autonomousActions: ["internal-read", "internal-write", "customer-message-send"],
    approvalRequiredActions: ["refund-create", "legal-advice-publish", "personal-data-export"],
    prohibitedActions: ["Diagnose or treat medical or mental-health conditions", "Provide crisis counselling beyond approved escalation guidance", "Expose one customer's data to another", "Promise an outcome outside published policy"],
    successMetrics: ["First response time", "Resolution time", "First-contact resolution", "Customer satisfaction", "Reopen rate", "Safety escalation accuracy"],
  },
  {
    id: "marketing",
    name: "Marketing",
    mission: "Research audiences and channels, create truthful content, and grow qualified demand through measurable campaigns.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#10B981",
    icon: "megaphone",
    capabilities: ["marketing.trends.research", "marketing.content.create", "marketing.content.publish", "marketing.community.respond", "marketing.campaigns.manage", "marketing.ads.manage"],
    allowedConnectorKinds: ["ai-provider", "email", "social-media", "messaging", "analytics", "content-storage", "commerce"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft"],
    approvalRequiredActions: ["public-content-publish", "ad-spend-change", "commercial-email-send"],
    prohibitedActions: ["Fabricate testimonials, engagement or results", "Use copyrighted assets without rights", "Target protected or vulnerable groups exploitatively", "Publish unsupported health, financial or spiritual claims"],
    successMetrics: ["Qualified reach", "Engagement quality", "Organic and paid conversion", "Customer acquisition cost", "Content-assisted revenue", "Brand-safety incidents"],
  },
  {
    id: "product-management",
    name: "Product Management",
    mission: "Turn validated orders and customer needs into safe, useful digital spiritual products and verifiable delivery plans.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#3B82F6",
    icon: "package",
    capabilities: ["product.orders.read", "product.research.perform", "product.requirements.write", "product.assets.generate", "product.personas.configure", "product.quality.verify", "product.delivery.release"],
    allowedConnectorKinds: ["ai-provider", "analytics", "content-storage", "commerce", "messaging"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft"],
    approvalRequiredActions: ["product-release", "public-content-publish", "contract-or-terms-change"],
    prohibitedActions: ["Ship unreviewed personalized spiritual or health guidance", "Clone a real person's voice or likeness without documented consent", "Use unlicensed source material", "Describe generated content as human-authored when disclosure is required"],
    successMetrics: ["Order-to-delivery time", "Acceptance rate", "Defect and refund rate", "Product activation", "Retention", "Safety and rights-review pass rate"],
  },
  {
    id: "legal",
    name: "Legal",
    mission: "Identify applicable law, review compliance and contracts, and route jurisdiction-specific decisions to qualified counsel.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#64748B",
    icon: "scale",
    capabilities: ["legal.law.research", "legal.compliance.review", "legal.contracts.review", "legal.privacy.review", "legal.ip.review", "legal.advice.publish"],
    allowedConnectorKinds: ["ai-provider", "content-storage", "analytics", "messaging"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft"],
    approvalRequiredActions: ["contract-or-terms-change", "legal-advice-publish", "tax-or-regulatory-filing", "personal-data-export"],
    prohibitedActions: ["Claim to be licensed counsel", "Give final jurisdiction-specific legal advice without qualified review", "File or sign on behalf of the company without authority", "Delete or conceal records subject to a hold"],
    successMetrics: ["Review turnaround", "Compliance coverage", "Open legal risk", "Contract exceptions", "Privacy incidents", "Qualified-counsel escalation accuracy"],
  },
  {
    id: "finance",
    name: "Finance",
    mission: "Maintain accurate books, payment visibility, controlled cash movement, forecasts and compliant financial reporting.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#22C55E",
    icon: "landmark",
    capabilities: ["finance.payments.read", "finance.payments.refund", "finance.payouts.create", "finance.invoices.manage", "finance.reconcile", "finance.forecast", "finance.reports.prepare", "finance.tax.prepare"],
    allowedConnectorKinds: ["ai-provider", "payment", "accounting", "commerce", "analytics", "messaging"],
    autonomousActions: ["internal-read", "internal-write"],
    approvalRequiredActions: ["refund-create", "payout-create", "bank-or-payment-settings-change", "tax-or-regulatory-filing", "credential-or-permission-change"],
    prohibitedActions: ["Move money outside configured limits", "Change settlement accounts autonomously", "File taxes without qualified review", "Alter or fabricate financial records"],
    successMetrics: ["Cash balance and runway", "Revenue and margin", "Reconciliation accuracy", "Receivables age", "Refund rate", "Budget variance"],
  },
  {
    id: "data-science-analytics",
    name: "Data Science & Analytics",
    mission: "Turn consented product, marketing and behavioral data into trustworthy recommendations that improve experience and conversion.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#06B6D4",
    icon: "chart-no-axes-combined",
    capabilities: ["analytics.sources.read", "analytics.events.define", "analytics.experiments.propose", "analytics.experiments.run", "analytics.reports.publish", "analytics.data.export", "analytics.pii.access"],
    allowedConnectorKinds: ["ai-provider", "analytics", "content-storage", "commerce", "crm"],
    autonomousActions: ["internal-read", "internal-write"],
    approvalRequiredActions: ["personal-data-export", "credential-or-permission-change"],
    prohibitedActions: ["Re-identify anonymized people", "Collect sensitive data without a lawful purpose", "Run manipulative dark-pattern experiments", "Report causal conclusions unsupported by the design"],
    successMetrics: ["Data quality", "Insight adoption", "Experiment velocity", "Conversion lift", "User-experience improvement", "Privacy-policy violations"],
  },
  {
    id: "seo-geo-aeo",
    name: "SEO, GEO & AEO",
    mission: "Improve discoverability in classic search, generative engines and answer engines using verified performance data, technically sound content, and truthful answers.",
    reportsTo: "ceo",
    canDelegateTo: [],
    color: "#8B5CF6",
    icon: "search-check",
    capabilities: [
      "search.performance.read", "search.queries.analyze", "search.pages.analyze",
      "search.intent.research", "search.content.brief.create", "search.structured-data.draft",
      "search.geo.optimize", "search.aeo.optimize", "search.content.publish",
    ],
    allowedConnectorKinds: ["ai-provider", "analytics", "content-storage"],
    autonomousActions: ["internal-read", "internal-write", "public-content-draft"],
    approvalRequiredActions: ["public-content-publish", "credential-or-permission-change"],
    prohibitedActions: ["Invent rankings, traffic, citations, backlinks or Search Console results", "Use deceptive cloaking, doorway pages, link schemes or keyword stuffing", "Publish unsupported health, financial or spiritual claims", "Change production content, structured data, indexing or credentials without approval"],
    successMetrics: ["Verified search impressions", "Verified organic clicks", "Search click-through rate", "Qualified organic conversions", "Answer coverage", "Cited generative-engine visibility"],
  },
] as const satisfies readonly DepartmentDefinition[];

export const DEPARTMENT_BY_ID = Object.fromEntries(
  SPIRITUAL_AI_DEPARTMENTS.map((department) => [department.id, department]),
) as Record<DepartmentId, (typeof SPIRITUAL_AI_DEPARTMENTS)[number]>;
