"use client";

import Link from "next/link";
import { Activity, ArrowRight, Building2, CircleDollarSign, ListChecks, ShieldCheck } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { RevenueSource } from "@/lib/revenue";
import type { WorkerRuntimeStatus } from "@/lib/factory-runtime";
import { DEPARTMENTS } from "@/lib/factory-blueprints";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
export function FactoryOverview({ revenue, worker }: { revenue: RevenueSource[]; worker?: WorkerRuntimeStatus }) {
  const departmentAgent = new Map((worker?.agents || []).map((agent) => [agent.departmentId, agent]));
  const runtimeIdForDepartment = (slug: string) => slug === "ceo-orchestrator" ? "ceo" : slug.replaceAll("-", "_");
  const connectorAnchorForRevenue = (id: RevenueSource["id"]) => id === "crypto" ? "coinbase_commerce" : id;
  const totalRevenue = revenue.reduce((sum, source) => sum + source.amount, 0);
  const logs = worker?.recentEvents || [];
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${worker ? "bg-emerald-400" : "bg-muted-foreground/40"}`} /><span className="text-sm text-muted-foreground">{worker ? "Factory worker online" : "Factory worker offline"}</span></div><h1 className="text-3xl font-semibold tracking-tight">Factory Overview</h1><p className="mt-1 text-sm text-muted-foreground">Revenue, agent activity, audit events, and department health.</p></div><Button asChild variant="outline"><Link href="/dashboard/connectors">Connect business systems <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></header>
    <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CircleDollarSign className="h-5 w-5" />Earnings by payment source</CardTitle><p className="text-sm text-muted-foreground">Only verified read-only payment data is included. Unsupported currencies remain excluded from USD totals.</p></CardHeader><CardContent><div className="mb-4 text-3xl font-bold tabular-nums">{money.format(totalRevenue)}</div><div className="h-[230px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenue}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `$${value}`} tickLine={false} axisLine={false} width={45} /><Tooltip formatter={(value) => money.format(Number(value))} /><Bar dataKey="amount" fill="hsl(var(--primary))" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Payment connections</CardTitle><p className="text-sm text-muted-foreground">Connect read-only sources from the interface.</p></CardHeader><CardContent className="space-y-3">{revenue.map((source) => <div key={source.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-medium">{source.label}</p><p className="mt-1 text-xs text-muted-foreground">{source.detail}</p></div><Badge variant={source.connected ? "success" : "secondary"}>{source.connected ? "Connected" : "Not connected"}</Badge></div>{!source.connected && <Button asChild className="mt-3 w-full" size="sm" variant="outline"><Link href={`/dashboard/connectors#${connectorAnchorForRevenue(source.id)}`}>Connect {source.label}</Link></Button>}</div>)}</CardContent></Card></section>
    <section className="grid gap-4 xl:grid-cols-[1.25fr_1fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5" />Factory activity log</CardTitle><p className="text-sm text-muted-foreground">Live audit events emitted by the local factory worker.</p></CardHeader><CardContent>{logs.length ? <div className="space-y-2">{logs.slice(0, 12).map((log) => <div key={log.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><p className="text-sm font-medium">{log.type.replaceAll(".", " ")}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{log.departmentId || "company"} · {log.actor}{log.taskId ? ` · task ${log.taskId.slice(0, 8)}` : ""}</p></div><time className="shrink-0 text-xs text-muted-foreground">{new Date(log.occurredAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div>)}</div> : <Empty text="No activity events are available yet." actionHref="/dashboard/agents" actionLabel="Open Agent activity" />}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ListChecks className="h-5 w-5" />Department status</CardTitle><p className="text-sm text-muted-foreground">Current task and runtime health by department.</p></CardHeader><CardContent><div className="space-y-2">{DEPARTMENTS.map((department) => { const agent = departmentAgent.get(runtimeIdForDepartment(department.slug)); const online = agent && ["running", "queued", "succeeded", "idle"].includes(agent.status); return <Link key={department.slug} href={`/dashboard/departments/${department.slug}`} className="flex items-center justify-between gap-3 rounded-lg border p-3 hover:bg-muted/50"><div className="min-w-0"><p className="text-sm font-medium">{department.shortName}</p><p className="truncate text-xs text-muted-foreground">{agent?.currentTask || agent?.lastTask || "No worker task"}</p></div><Badge variant={online ? "success" : "secondary"}>{agent?.status || "Offline"}</Badge></Link>; })}</div></CardContent></Card></section>
    <section className="grid gap-4 md:grid-cols-[.8fr_1.2fr]"><Link href="/dashboard/departments/ceo-orchestrator" className="group rounded-xl border bg-gradient-to-br from-primary/15 to-background p-6 transition-colors hover:border-primary"><div className="flex items-center justify-between"><Building2 className="h-8 w-8 text-primary" /><ArrowRight className="h-5 w-5 text-muted-foreground group-hover:text-primary" /></div><h2 className="mt-5 text-xl font-semibold">CEO Cabin</h2><p className="mt-1 text-sm text-muted-foreground">Open the executive orchestration room for company objectives, decisions, and escalations.</p></Link><Link href="/dashboard/departments" className="group rounded-xl border p-6 transition-colors hover:bg-muted/50"><div className="flex items-center justify-between"><ShieldCheck className="h-8 w-8 text-primary" /><ArrowRight className="h-5 w-5 text-muted-foreground group-hover:text-primary" /></div><h2 className="mt-5 text-xl font-semibold">Departments</h2><p className="mt-1 text-sm text-muted-foreground">Browse and configure all {DEPARTMENTS.length} AI Factory departments.</p></Link></section>
  </div>;
}
function Empty({ text, actionHref, actionLabel }: { text: string; actionHref?: string; actionLabel?: string }) { return <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground"><p>{text}</p>{actionHref && actionLabel && <Link href={actionHref} className="mt-2 inline-block font-medium text-primary hover:underline">{actionLabel} <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></Link>}</div>; }
