"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Inbox, Loader2, Mail, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Candidate = { id: string; email: string; name?: string; event: string; product?: string; accessUrl?: string; reason: string };
type Log = { id: string; direction: "sent" | "received"; status: string; recipient: string; subject: string; event: string; preview: string; occurredAt: string; error?: string };
type Payload = { connected: boolean; candidates: Candidate[]; logs: Log[]; detail?: string };
const label: Record<string, string> = { recommendation: "Recommendation", trial_ready: "Trial ready", trial_ended: "Trial ended", purchase_started: "Purchase", product_ready: "Product ready", subscription_review: "Review request" };

export function MailOperationsConsole({ authenticationConfigured }: { authenticationConfigured: boolean }) {
  const [data, setData] = useState<Payload>(); const [loading, setLoading] = useState(false); const [sending, setSending] = useState<string>(); const [error, setError] = useState<string>();
  async function refresh() { if (!authenticationConfigured) return; setLoading(true); setError(undefined); try { const response = await fetch("/api/mail", { cache: "no-store", credentials: "same-origin" }); const payload = await response.json() as Payload & { error?: string }; if (!response.ok) throw new Error(payload.error || "Could not load mail operations."); setData(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load mail operations."); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [authenticationConfigured]);
  async function send(candidate: Candidate) { setSending(candidate.id); setError(undefined); try { const response = await fetch("/api/mail", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify(candidate) }); const payload = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(payload.error || "Email was not sent."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Email was not sent."); } finally { setSending(undefined); } }
  const logs = data?.logs || []; const sent = logs.filter((log) => log.direction === "sent" && log.status === "sent").length; const received = logs.filter((log) => log.direction === "received").length;
  return <section className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex gap-2"><Badge variant="outline">Lifecycle mail</Badge><Badge variant="secondary">Transactional only</Badge></div><h1 className="text-3xl font-bold tracking-tight">Mail Department</h1><p className="mt-2 max-w-3xl text-muted-foreground">Reads approved lifecycle signals, drafts personalized product mail, sends through your transactional provider, and keeps an encrypted sent and received-mail timeline.</p></div><Button variant="outline" onClick={() => void refresh()} disabled={loading || !authenticationConfigured}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}Refresh signals</Button></div>
    {!authenticationConfigured && <p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-muted-foreground">Configure Clerk login and sign in to operate lifecycle mail.</p>}{error && <p role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="pt-6"><p className="text-xs text-muted-foreground">Ready to send</p><p className="mt-2 text-2xl font-bold">{data?.candidates.length || 0}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs text-muted-foreground">Sent lifecycle mail</p><p className="mt-2 text-2xl font-bold">{sent}</p></CardContent></Card><Card><CardContent className="pt-6"><p className="text-xs text-muted-foreground">Received mail</p><p className="mt-2 text-2xl font-bold">{received}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Mail className="h-5 w-5" />Lifecycle queue</CardTitle><p className="text-sm text-muted-foreground">{data?.detail || "Connect the customer database to discover lifecycle signals."} Each send is deduplicated by its verified lifecycle event.</p></CardHeader><CardContent className="space-y-3">{data?.candidates.length ? data.candidates.map((candidate) => <div key={candidate.id} className="flex flex-col gap-3 rounded-lg border p-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{candidate.name || candidate.email}</p><Badge variant="outline">{label[candidate.event] || candidate.event}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{candidate.email}{candidate.product ? ` · ${candidate.product}` : ""}</p><p className="mt-2 text-xs text-muted-foreground">{candidate.reason}</p></div><Button size="sm" onClick={() => void send(candidate)} disabled={Boolean(sending)}>{sending === candidate.id ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Send email</Button></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No eligible lifecycle messages are waiting.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Inbox className="h-5 w-5" />Mail history</CardTitle><p className="text-sm text-muted-foreground">Inbound mail is captured by the authenticated webhook; delivery attempts and provider errors are retained here.</p></CardHeader><CardContent className="space-y-2">{logs.length ? logs.slice(0, 100).map((log) => <div key={log.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge variant={log.status === "failed" ? "destructive" : log.direction === "received" ? "secondary" : "success"}>{log.direction === "received" ? "Received" : log.status}</Badge><p className="text-sm font-medium">{log.subject}</p></div><p className="text-xs text-muted-foreground">{new Date(log.occurredAt).toLocaleString()}</p></div><p className="mt-1 text-xs text-muted-foreground">{log.recipient} · {log.preview}</p>{log.error && <p className="mt-1 text-xs text-destructive">{log.error}</p>}</div>) : <div className="flex flex-col items-center py-10 text-center text-muted-foreground"><CheckCircle2 className="h-8 w-8" /><p className="mt-3 text-sm">No mail has been sent or received yet.</p></div>}</CardContent></Card>
    <p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4" />Sending requires <code>RESEND_API_KEY</code> and <code>MAIL_FROM_ADDRESS</code>. Incoming webhook requests require <code>MAIL_INBOUND_WEBHOOK_SECRET</code>.</p>
  </section>;
}
